name: Maven Release

# https://stackoverflow.com/questions/58254332/maven-release-from-github-actions
on:
  workflow_dispatch:
    branches: [ "master" ]
    inputs:
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "X.Y.Z"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "X.Y.Z-SNAPSHOT"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Log the Input
        run: |
          echo "### Creating new Tag: $Tag"
          echo "### Creating new Snapshot: $Snapshot"
        env:
          Tag: ${{ inputs.releaseVersion }}
          Snapshot: ${{ inputs.developmentVersion }}
          
      - uses: actions/checkout@v3
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
      
      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Maven Release
        run: mvn -B release:prepare release:perform -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
