# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Maven Build

on:
  workflow_dispatch:
  push:
    branches: [ "master", "feature/**" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
      
    # This action installs the given version of the JDK into the PATH, and also sets up a Maven settings.xml for publishing the package to GitHub Packages. 
    # The generated settings.xml defines authentication for a server with an id of github, using the GITHUB_ACTOR environment variable as the username and 
    # the GITHUB_TOKEN environment variable as the password. The GITHUB_TOKEN environment variable is assigned the value of the special GITHUB_TOKEN secret.
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml.
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: Set Maven Versions
      id: set_version
      run: |
        # make file runnable, might not be necessary
        chmod +x "${GITHUB_WORKSPACE}/.github/workflows/scripts/set_mvn_version.sh"
        # run set version script
        "${GITHUB_WORKSPACE}/.github/workflows/scripts/set_mvn_version.sh"
    
    - name: Run Maven Install
      run: |
        mvn -B versions:set -DnewVersion="${{ steps.set_version.outputs.BRANCH_MVN_VERSION }}"
        mvn -B install
        docker version
    
    - name: Run Maven Deploy
      run: |
        mvn -B versions:set -DnewVersion="${{ steps.set_version.outputs.BRANCH_MVN_VERSION }}"
        mvn -B deploy -s $GITHUB_WORKSPACE/settings.xml  
      env:
        GITHUB_TOKEN: ${{ github.token }}  
      
    - name: Run Sonar
      run: mvn clean verify sonar:sonar -Pcoverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
      
