name: Maven Release

# https://stackoverflow.com/questions/58254332/maven-release-from-github-actions
on:
  workflow_dispatch:
    # TODO: the restriction to branch master does not work. find a way to enforce that release can only be triggered within master
    branches: [ "master" ]
    inputs:
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "X.Y.Z"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "X.Y.Z-SNAPSHOT"

jobs:
  release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      packages: write

    steps:
      - name: Log the Input
        run: |
          echo "### Creating new Tag: $Tag"
          echo "### Creating new Snapshot: $Snapshot"
        env:
          Tag: ${{ inputs.releaseVersion }}
          Snapshot: ${{ inputs.developmentVersion }}
          
      - uses: actions/checkout@v3
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }}/.github/.m2/github # location for the settings.xml file. Default is ~/.m2/settings.xml
          # TODO: provide a variable for the github settings.xml location
          
      - name: Setup Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v21
        with:
          servers: >
            [
              {
                "id": "central",
                "username": "${ARTIFACTORY_USERNAME}",
                "password": "${env.ARTIFACTORY_TOKEN}"
              },
              {
                "id": "snapshots",
                "username": "${ARTIFACTORY_USERNAME}",
                "password": "${env.ARTIFACTORY_TOKEN}"
              },
              {
                "id": "github",
                "username": "${env.GITHUB_ACTOR}",
                "password": "${env.GITHUB_TOKEN}"
              }
            ]
          output_file: ${{ github.workspace }}/.github/.m2/artifactory/settings.xml # by default it goes to ~/.m2/settings.xml
          # TODO: provide a variable for the artifactory settings.xml location    
      
      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Maven Release
        continue-on-error: true # TODO: currently release is failing when uploading released pom
        run: |
          mvn -version
          echo "### Release started. Released Version ${{ github.event.inputs.releaseVersion }}. New Snapshot is: ${{ github.event.inputs.developmentVersion }}"
          mvn -B -e release:prepare release:perform -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }} -Partifactory -s $GITHUB_WORKSPACE/.github/.m2/artifactory/settings.xml
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
          
      - name: Get Deployable
        # orig: curl 'https://maven.pkg.github.com/boeckli-swp/wsl-java11/org/example/wsl-java11/${{ github.event.inputs.releaseVersion }}/wsl-java11-${{ github.event.inputs.releaseVersion }}-spring-boot.jar' \
        run: |
          echo "### Retrieving deployable jar ###"
          curl 'https://boeckli1.jfrog.io/artifactory/local-maven-release-repo/org/example/wsl-java11/${{ github.event.inputs.releaseVersion }}/wsl-java11-${{ github.event.inputs.releaseVersion }}-spring-boot.jar' \
            -H "Authorization: Bearer ${{ secrets.ARTIFACTORY_TOKEN }}" \
            -L \
            -o target/deployable.jar
          ls -la target
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
